// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "common/lib/env"
import { defineConfig } from "prisma/config"
import { env } from "common/lib/env"

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: env.DATABASE_URL,
  },
})
